### ISSUE TITLE
gui() command not working - wmic not found

### ISSUE THREAD

**Issue by ShauryaBajaj** [sylvainschmitt/SSDM#15]
Hello @sylvainschmitt ,
After installing the SSDM package, the gui() command isnt functioning with the following error. If you could provide some insights it would be helpful. I am using Windows 8.1 pro on a Sony Vaio laptop.
I Tried looking for a solution but couldnt find one. Even tried adding variable representing wmic in env path (I dont think this would be a solution).

![image](https://user-images.githubusercontent.com/24893975/35860569-904e50bc-0b6a-11e8-90c0-1be71d2841e3.png)

**Comment by sylvainschmitt** [comment]
It is a system error and more especially it seems linked to your OS (Windows). Consequently because it does not concern `SSDM` itself and I am linux user, I am afraid I won't be able to help you. Anyway Internet seems fool of similar issues (see [1](https://www.howtogeek.com/forum/topic/wmic-not-recognized-as-an-internal-or-external-command) for instance). In addition the issue seems to come from `shinyFiles` dependency used in the Graphical User Interface (GUI). See the [issue 40](https://github.com/thomasp85/shinyFiles/issues/40) for instance. So maybe you can contact them. I wish you good luck. I will close the issue because it is not regarding `SSDM` but a dependency. But if you find a solution, it would be great you add it in this thread.
