### ISSUE TITLE
GUI: Cannot launch modeling with 'None' option for endemism mapping

### ISSUE THREAD

**Issue by dimitri-justeau** [sylvainschmitt/SSDM#2]
Using the GUI, if I try to launch a modeling with 'None' selected for the endemism mapping parameter, I get this error:

```
Warning: Error in .checkargs: endemism parameter should be Any, WEI, or CWEI (see help).
Stack trace (innermost first):
    69: .checkargs
    68: stack_modelling
    67: eval
    66: eval
    65: withProgress
    64: observeEventHandler [/usr/local/lib/R/site-library/SSDM/shiny/gui/server.R#556]
     2: shiny::runApp
     1: gui
```

It seems like 'None' isn't defined as an option for this parameter in the code?

**Comment by sylvainschmitt** [comment]
The issue come from the fact that in version 0.1.9016 the endemism parameters change (from one simple character string to a double character string) due to the doubt of interpretation around the term range and to let the user choose. But the `.checkargs` function responsible to check the validity of function arguments hasn't been updated. But regarding the 'None' choice in the gui, no issue once the update done it will work, because 'None' in the interface is translated by the server as 'Any' or NULL.

Thank you for noticing the issue, I'll fix the bug soon.

**Comment by sylvainschmitt** [comment]
Bug fix committed.
