### ISSUE TITLE
GUI crashed during long computation

### ISSUE THREAD

**Issue by asnyder5** [sylvainschmitt/SSDM#27]
After several days, my SSDM run has completed. However I am unable to save the results. The webpage screen has turned to grey and when clicking on "folder selection" I am unable to make a new folder. The original working directory folder does not appear there either. Before, a separate window would pop up saying "DataTables warning: table id=DataTables_Table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7" 

Have I lost everything that I just spent the last few days running or is there a way to recover and save my results?

**Comment by sylvainschmitt** [comment]
You say the webpage is grey, meaning that the server crashed. I can't know why with so few details but R was still running correctly at this stage or R was crashed too ? Anyway I do not recommend usnig the GUI for very long computation (besides in theory it should work). You may not have lost everything because temporary files are saved during the process, and if you did not have reboot they might be still here. Anyway temporary files are only raster maps, meaning you lost all others information. So I'll advice to run again the model through command line this time.

**Comment by asnyder5** [comment]
Hi Sylvain,

I refused to give up on it and seemed to have found the error having now successfully run many different models. It seemed as though I would have this issue whenever I set my working directory in R before installing the necessary packages and accessing the gui() interface. When I opt not to do this and manually direct the gui() to my folders for environmental variables and occurrences I no longer had the issue. I also didn't try to make a new folder and rather just saved it to my desktop.

**Comment by sylvainschmitt** [comment]
Okay you have different informations: 

> issue whenever I set my working directory in R before installing the necessary packages and accessing the gui()

Could you sort if the issue is due to package installation or gui launch ? Personally I suspect it's more probable to be linked to the gui, because I effectively struggled to make working directory works. So what is precisely your issue ? When you set manually the working directory before launching the gui, the model crash or you can't save the model ? And what is your configuration ? Do you work on Windows ? Do you set your working directory on you main hard drive (i.e. C://) or another ?
