### ISSUE TITLE
Time to open clusters

### ISSUE THREAD

**Issue by timothyharris** [sylvainschmitt/SSDM#30]
I ran the following script:

SSDM <- stack_modelling(c('MAXENT'), Occurrences = Occ, Env, rep =2, Xcol = "decimalLongitude", Ycol = "decimalLatitude", Spcol = "scientificName", method = "pSSDM", range = 30, endemism = NULL )

After six days running on a powerful computer (8GB memory 3.6GHz processor) it still at the "Opening clusters" stage. Have I done something wrong?

I am modelling 200 species. Apologies if this is a stupid question.

**Comment by sylvainschmitt** [comment]
No that's not normal because as soon as it open the cluster you should have a message for the first species model beginning. It means that your command is stuck at the cluster opening or the cluster export stage. But you are not working on a cluster but on a personal computer. Is your environmental variables large it could explain a memory overload, because each cluster node will have an export of environmental and occurrences data. try to parallelize on only two cores first.

**Comment by timothyharris** [comment]
Thank you so much for responding. Would you be able to point me in the direction of reading about how control how the cores are used?
