### ISSUE TITLE
Null division in project method

### ISSUE THREAD

**Issue by asierrl** [sylvainschmitt/SSDM#35]
I run a ensemble model with 5 different methods (GLM, GAM, MARS, CTA and ANN) and a list of 10 environmental rasters, with 143 presence/absence points. Everything seems to work properly but all three maps (projection, uncertainty and binary) appear empty. How can I find what the problem is? I set verbose to TRUE, but most of the console output is unavailable due to the limit of the number of lines. 
Thanks a lot.
Asier

**Comment by asierrl** [comment]
Thanks a lot, Sylvain. Unfortunately, it doesn't seem to happen all the time, so that I'll need to wait until it happens again. Actually it actually happened to me now, but when before I tryed to save the console Windows crashed. Next time!! 
The only thing I saw in this model (the remaining of model output seems ok) is that ANN has only 3 kept models (out of 10) and displays NAs in algorithm.correlation. Equally (and not surprisingly), min and max values for uncertainty, projection and binary slots are NA. May be that the reason?

**Comment by asierrl** [comment]
I managed to reproduce the issue and save the console to a file, thanks to your link. I provide it here:
[console.txt](https://github.com/sylvainschmitt/SSDM/files/2473925/console.txt)

Thanks a lot...
Asier

**Comment by lukasbaumbach** [comment]
@asierrl  Depending on the ensemble.threshold and the ensemble.metric you selected, it is very well possible, that quite a few of your models fell below that threshold (default=0.75). It happened to me before. From a quick look at your console output, it also appears that many ANN models did not converge (as you realised only 3 were kept). Try lowering the threshold (worst case down to zero) and see if it's keeping the models. If not, there may be another problem.

**Comment by asierrl** [comment]
Thanks a lot, Lukas.
I already managed to avoid the issue but I don't know how, really. I'm not sure if the problem come from some of the models not reaching the threshold. In fact, that happens often and I still get valid projection, binary and uncertainty maps. In fact, I even have a case where only one of the models is valid, and I still get valir projection and binary maps, although not, of course, uncertainty map.
Thanks for your help, anyway.
Asier

**Comment by lukasbaumbach** [comment]
@asierrl Hi, just a short update: I had the issue again today and tried tracking it down. It appears, that a single empty projection lead to a propagation of NAs throughout the projections and caused the diversity map to be empty, too. 
@sylvainschmitt I looked closer into the origin of the NA projection: the model had a good discrimination (AUC=0.8), but was probably overfitted/very sensitive. Since for one species the maximum value was 0  (might also happen with better models under strong climate scenarios), the rescaling caused a 0 divided by 0 problem - with NAs as a result. Through sum and mean, this leads to empty ensemble and diversity maps. Inserting a conditional phrase `if (projection@data@max>0){projection = projection / projection@data@max}` would maybe help avoiding this.

**Comment by sylvainschmitt** [comment]
@lukasbaumbach , @SMonsarrat in #46 also noticed the `NA`s propagation resulting in an empty diversity map. She suggested to add a `na.rm = TRUE` in diversity mapping methods. I think we should do it, but better to ignoring `NA`s is to find their origin. And thank you, I think that's what you just did ! So we should also add your suggestion `if (projection@data@max>0){projection = projection / projection@data@max}` in the project method. Do you think you would be able to implement it, test it with automatic tests including in the package structure with `devtools:test()`, and request a push to my repository ? If not I'll do it and I will be happy to have you test it to see if it solves your issue.
Best,
Sylvain

**Comment by lukasbaumbach** [comment]
@sylvainschmitt Since I am working on the project function anyways (that's how I discovered it), I can do it. Should I make a new test (never did that before) for the project function or just run the ones in the testthat folder?

**Comment by sylvainschmitt** [comment]
Great ! You just have to run the existing function (but they wont hit the case where the maximum is 0 because I never detected the test before, it will just check that you are not breaking the existing code with your implementation). Anyway when you'l send a pull request Travis-CI will test the code too. And try to update the NEWS if possible. Thanks a lot in advance.

**Comment by lukasbaumbach** [comment]
I'm having some troubles creating a pull request, since I forked the repository earlier. I made quite a lot of commits in there lately (also wanted to give you an update on that soon), so I can't create a pull request from there. Do you know a different way (e.g. creating a 2nd fork or pulling from a repository, which isn't a fork)?

**Comment by sylvainschmitt** [comment]
I don't see what is your issue ? You want to pull request your repository called [SSDM1](https://github.com/lukasbaumbach/SSDM-1) ? In order to do that you just have to click on Pull Requests tab and [create a pull request](https://github.com/lukasbaumbach/SSDM-1/compare) (you can use directly the link from this post). You should have something similar to [this](https://github.com/sylvainschmitt/SSDM/compare/Forecasting-%2342...lukasbaumbach:master). I'll just have to requests: (i) rename your repository in SSDM as you are working on the same version (GitHub will acknowledged that it's your work forked from my repository, but it's the same package so it should kept its name), and (ii) make your pull requests to the branch named `Forecasting-#42` and not the `master` branch. As it is a new development I prefer to keep it on a separate branch and only integrate it to the `master` when finished (probably with a new CRAN version). Last but not least, it's okay if you are making lot of  commits (commit as you wish), but try to have not too many changes in each pull request, because it's easier for me to check few changes than a lot of code refactoring (if it's not the case for this one try to keep it in mind for next ones). Good luck, Sylvain
