### ISSUE TITLE
Model replications

### ISSUE THREAD

**Issue by lukasbaumbach** [sylvainschmitt/SSDM#43]
Since the `modelling` function only allows for building single SDMs without replicates, the only way to build several replicates of the same modeling algorithm currently is to use the `rep` argument of the `ensemble` function. However, Ensemble.SDMs don't store the single models, so model information cannot be accessed afterwards. To overcome this issue and also facilitate potential model projection (as discussed in issue [#42](https://github.com/sylvainschmitt/SSDM/issues/42)), it would be nice to extend or edit the `modelling` function so it could also produce replicates. Here's a dummy example:
```{r}
SDMS <- modelling("GLM", Occurrences, Env, rep=10)
# SDMS is a list with 10 objects of type Algorithm.SDM
```

**Comment by sylvainschmitt** [comment]
I disagree on this one, and I think you are mixing two different issues:
* You want to store single models SDMs in the final ESDM
* You want to do models with repetition of a single algorithm
And the second for me is an ESDM beside you have only one algorithm, because with repetitions you still have an ensemble of distribution models. So I suggest to close the issue and develop to keep SDMs within ESDMs (as needed for #42), and you'll have approximately the behavior you need:
```
ESDM <- ensemble_modelling("GLM", Occurrences, Env, rep = 10)
# ESDM@SDM is a list with 10 objects of type Algorithm.SDM
```
