### ISSUE TITLE
method for summing probabilities in pSSDM

### ISSUE THREAD

**Issue by VirginiaMorera** [sylvainschmitt/SSDM#56]
Hello again, 

I was wondering how the habitat suitability rasters are being summed when `method = "pSSDM"` is specified in the `stack_modelling()` function. From the manual: 
>pSSDM sum probabilities of habitat suitability maps

but since these are probabilities the sum should not be a straightforward sum, right? 

If I have three species (A, B, and C) and their probability of presence: P(A), P(B) and P(C), the probability of finding either of them should not be P(A) + P(B) + P(C) but 

P(A U B U C) = P(A) + P(B) + P(C) - P(A + B) - P(A + C) - P(B + C) + P(A + B + C)

right? Or am I just overthinking this?

**Comment by sylvainschmitt** [comment]
As written and you correctly understood pSSDM is the probability sum and not union. I have not the time and it's not the place to discuss the theory behind because SSDM is an implementation of the literature methodology. I invite you to have a look to the [corresponding article](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12841) and more especially cited references for pSSDM method:
>The final maps of local species richness and composition can be computed using six different methods: [...] (3) by summing continuous habitat suitability maps (pSSDM) (e.g. Mateo et al., 2012; Murray‐Smith et al., 2009; Pouteau, Bayle, et al., 2015; Schmidt‐Lebuhn et al., 2012)
