### ISSUE TITLE
Comparing modeled species assemblages with species pools from inventories observed in the field

### ISSUE THREAD

**Issue by jgiovanelli** [sylvainschmitt/SSDM#59]
Dear Sylvain,

The SDDM provides the opportunity to compare modeled species assemblages with species pools from independent inventories observed in the field. However, I did not find this information in the reference manual. Could you tell me the code to do this analysis?
Thanks

**Comment by lukasbaumbach** [comment]
@jgiovanelli This is probably quite a late answer, but for the record: SSDM is intended to model species individually and stack the results into species diversity maps. It also provides different evaluation criteria to assess the overall performance of the model stack. You can find these in the `@evaluation` slot of your SSDM object. A post-hoc comparison of the SSDMs with independent species inventories to my knowledge is not directly possible from within the package. Since the new version (v0.2.8., just updated), there is new options to evaluate the individual SDMs with test data (via 'holdout'), however.

**Comment by sylvainschmitt** [comment]
@jgiovanelli sorry for the late answer, but it isn't implemented for the moment and is not scheduled (besides it's totally legitimate and a good idea). You may however derivate the current code used for community evaluation:

https://github.com/sylvainschmitt/SSDM/blob/6ed453e9b0705301f64d55826ba6a2072db5f842/R/evaluate.R#L429-L489

It's easier to say than to do. A complicated way would be to change the data in `obj@esdms@data` by the one you want to use as evaluation data (a bit too complicated I think). A second way is to use the previous code to compute the community prediction at your evaluation points, and then used the previous code to generate the confusion matrix and the resulting metrics: species richness error, prediction success, kappa, specificity, sensitivity and Jaccard.
