### ISSUE TITLE
Manual pseudo-absences ?

### ISSUE THREAD

**Issue by FedericoRiva** [sylvainschmitt/SSDM#65]
Dear Sylvain,
I am running a series of models with the stack_modeling function using the Maxent algorithm. Is there a way to incorporate a Bias surface while sampling the pseudo-absences, or to provide the pseudo-absences myself?  I tried using the "args= c()" as in dismo providing the raster bias, is this the proper way?

Thank you for your time and consideration.
Kind regards,
Federico

**Comment by sylvainschmitt** [comment]
You'll have to be more explicit, you want to provide pseudo-absence manually ? The `SSDM` package was not originally thought for it, but you can still do it by building yourself your `SDM` objects and use the `model` function on it. You can inspire from a test I built:
https://github.com/sylvainschmitt/SSDM/blob/714b83a0d5bc5bf21ab09445988837aab24b7c8d/tests/testthat/test_Algorithm.SDM.R#L2-L22
Do the same but at the step where I call `PA.select` method to generate the pseudo-absences, you can enter yourself your pseudo-absences. Pseudo-absences are just a data frame with X, and Y coordinates and 0 for presence that you append to the model presence data:
https://github.com/sylvainschmitt/SSDM/blob/714b83a0d5bc5bf21ab09445988837aab24b7c8d/R/PA.select.R#L53
I am certainly not totally clear, don't hesitate to ask more detail. And best, you can built a minimal example with the data from the package where you input yourself pseudo-absences, and if you'll have issues I will be able to help you on the minimal example.

**Comment by sylvainschmitt** [comment]
@lukasbaumbach , I don't think it's really useful but manual pseudo-absences input could be a future enhancement in the package

**Comment by lukasbaumbach** [comment]
@FedericoRiva Unfortunately, fine-tuning MaxEnt parameters through the SSDM functions is not possible at the moment. However, you can easily supply your own pseudo-absences. Just add a 'presence' column to your data set with 1 for presences and 0 for absences, then just give the name of the 'presence' column to the `Pcol` argument (it's in all `*modelling` functions). The function will automatically detect, that you are using presence-absence data.

@sylvainschmitt :
1) I also work with manual pseudo-absences, since the sampling strategies provided by the package do no fit my methodology. Generally I think it's fine that way we don't need to provide more strategies in `PA`. However, especially for having model replicates, it could be worth rewriting the `rep` part of `ensemble_modelling` a little. Because right now, if I use it with manual PA-data, I will mostly get the same models (depending on the algorithms I use), since the modelling function always uses the full data set after running the cross-validation tests (set with `cv.param`). It would be nice to have the same feature as in `cv.param` for the final models, too.
2) we could think about just adding a `args=c()` argument in the `get_model` function. Should be an easy fix.

**Comment by sylvainschmitt** [comment]
> Unfortunately, fine-tuning MaxEnt parameters through the SSDM functions is not possible at the moment.

In fact we could add some `MaxEnt` options through the `...` argument capture in the `modelling`  and `get_model` function:
https://github.com/sylvainschmitt/SSDM/blob/714b83a0d5bc5bf21ab09445988837aab24b7c8d/R/get_model.R#L114-L124

**Comment by FedericoRiva** [comment]
I will work on the model based on your recommendations. The solution of adding a series of 0s to the original data seems exactly what I need. I will try also to build the object model as suggested by Sylvain. Unfortunately I don't think it's possible to provide the argsc() argument in stack_modelling, the function I am interested in using for this specific study.
Cheers,
Federico
