### ISSUE TITLE
problems with PA

### ISSUE THREAD

**Issue by mathildehure** [sylvainschmitt/SSDM#67]
Hello, 

I am currently using your SSDM package to model the distribution of favorable habitats for an endemic passerine on the island of Réunion. I only have presence data of the species and therefore I have to use the pseudo-absence argument. I read in the recommended article (Barbet-Massin et al., 2012) that for GLM for example it was good to put a lot of pseudo-absences. However, when I try to run the following function, the command remains locked : 

GAM <- modelling('GAM', Occ ,Env, Xcol = 'X', Ycol='Y', Pcol='Presence', name='GAM_PNB', PA = list('nb'=4000,'strat'='random'))
Data check ... 
Pseudo-absence selection will be computed.
  done. 

Pseudo absence selection... 
  random selection

I can let it run for several minutes or an hour and nothing happens ... Would you have a solution to bring me?

**Comment by sylvainschmitt** [comment]
Sorry but i can't help you with so few information. Just, if you let PA with the default value you know it will process as recommended by Barbet-Massin et al., 2012 ? Could you provide me the version number of the `SSDM` package you use ? In addition can you run the minimal example (in the help of `?modelling`) and tell me if everything worked ? And if the minimal example works, it means there is an issue related to your data set, in which case could you describe a bit your data (environmental data range and resolution and number of observations) ?

**Comment by mathildehure** [comment]
I am using version 0.2.4. I ran the minimal model and everything worked. In my data file I only have my two columns for latitude and longitude, all of my data are points of occurrence, in total I have 4240 georeferenced points. As environmental data I use numerical and categorical variables (which I specified in my script) with a resolution of 100 meters: altitude, shading, geology, rainfall, habitats and slope. I have also just tried to leave the default values and the command is still blocked, there is no bug but just it tells me indefinitely that it loads ...

**Comment by sylvainschmitt** [comment]
You can try to update `SSDM` to version 0.2.6 but I'm pretty sure it won't solve your odd issue. Could you give me the outputs of following commands:
```
summary(Occ)
summary(Env)
```
The pseudo-absences selection with random strategy being pretty simple I don't see how is it possible that your code is stuck there. The only possible way I'll see the for loop to get stuck is if your first environmental variable used as mask is full of missing data (NA):
https://github.com/sylvainschmitt/SSDM/blob/714b83a0d5bc5bf21ab09445988837aab24b7c8d/R/PA.select.R#L37-L53
But that's very unlikely. I'll wait to see the outputs of your data summary. If you are really stuck and you are in a hurry, you can manually generate your pseudo absences and input them (but that would be a shame as the pacakge was designed to do it...) following the advice given in #65 .

**Comment by sylvainschmitt** [comment]
Oh I just noticed that I reported a bug in my code comments:
> A bug can appear here if obj@data coordinates are consider as factors, 
> it can happen if occurences are not well loaded and decimal is not well defined 
You will quickly see with `summary(Occ)` if X and Y columns are considered as factors.

**Comment by mathildehure** [comment]
Voici ce que j'obtiens en faisant summary(Occ) : 

> summary(Occ)
       X                                    Y          
 Min.   :331987         Min.   :7667828  
 1st Qu.:334956      1st Qu.:7678990  
 Median :337699     Median :7679729  
 Mean   :336938      Mean   :7679782  
 3rd Qu.:338412      3rd Qu.:7680298  
 Max.   :549470       Max.   :7980838  

et effectivement j'obtiens des NA quand je fais summary(Env), ce qui est bizarre puisque lorsque je fais summary(Env$aspect100) par exemple il m'indique que je n'ai aucun NA... : 

> summary(Env)
                             alti100       aspect100              Geol100         pluvio100       slope100       Vegedecoup
Min.                          0              8.616466e-02        0                 451.5423       0.000000                0
1st Qu.                     0               8.163416e+01        0                 1485.9724    0.000000                 0
Median                    66             1.867099e+02      10                2655.5369    3.032137                  6
3rd Qu.                    877            2.637731e+02      12                4488.9941   11.541067                20
Max.                       3036           3.600000e+02     170             10863.5176   69.967621               24
NA's                           0               2.013380e+05  203704             204072            2871               85590

> summary(Env$aspect100)
           aspect100
Min.      0.09630066
1st Qu.  81.86994171
Median  186.84280396
3rd Qu. 264.49582672
Max.    360.00000000
NA's      0.00000000

**Comment by sylvainschmitt** [comment]
I think it's my last comment:
>A bug can appear here if obj@data coordinates are consider as factors,
it can happen if occurences are not well loaded and decimal is not well defined

I don't know you coordinate system but X between 331987 and 549470 seems to lack a decimal. Check your occurrences data import.

**Comment by mathildehure** [comment]
Actually there were two misinformation points that's why X was between 331987 and 549470. I projected all my points on the image of one of my rasters corresponding to an environmental variable and it would seem they are well loaded and I do not think it's missing a decimal... 

![Capture d’écran 2019-10-10 à 14 16 23](https://user-images.githubusercontent.com/56350477/66560719-fb7e5f00-eb68-11e9-81a3-2c63fd2aaa47.png)

**Comment by sylvainschmitt** [comment]
Is this the raster of `plot(Env[[1]])` or did you do it with other not processed variables ? By default `SSDM` uses `Env[[1]]` as the mask variable in which to select pseudo-absences. But I don't get why you don't have any NA for alti100, it means that you consider sea in your distribution, you shouldn't. That's still doesn't explain to me why the function get stuck in the while loop. If you have a bit of time, because I'm already spending too much on my side for what seems to be a user specific issue, try to run manually the PAselect function. Copy and run the following code with your data:
https://github.com/sylvainschmitt/SSDM/blob/714b83a0d5bc5bf21ab09445988837aab24b7c8d/R/PA.select.R#L17-L53
But instead of running the while loop, run the block one time and look at the summary of `points` and `check`. I'm assuming the issue is that `check` will be always be full of NA, thus getting the while loop stuck. But it's better to test it to be sure, in case the issues lays elsewhere.

**Comment by mathildehure** [comment]
Ok I will test your code and try other ways. 

I really thank you for your help and the time you have given me.

**Comment by guilherme-atencio** [comment]
I don't know if it helps anyone, but I found out I have the same issue if the variable I am using has the value 255 as nodata. It seems like QGIS assumes this as default for some operations.
Changing it back to 0 fixed the loop for me.
Hope it helps.
Thanks

**Comment by hooge104** [comment]
I think the issue lies in the selection of PA points (2°far method; Barbet-Massin 2012). The way it's implemented in PA.select.R right now (line 29-30), does the opposite of what it should do (I think):
https://github.com/sylvainschmitt/SSDM/blob/714b83a0d5bc5bf21ab09445988837aab24b7c8d/R/PA.select.R#L17-L34

This creates a mask that only retains pixels that fall _within_ 2 degrees from each observation; but it should return a mask that has pixels that are _not within_ 2 degrees from each observation.

As an example: Red dots are observations, blue dots pseudo-absences. To create this example I manually set `nb=10000000', from which just 125 fell within the mask:
<img width="588" alt="Screenshot 2019-11-25 at 15 01 54" src="https://user-images.githubusercontent.com/37101570/69546704-8a69fe00-0f94-11ea-8abe-a67d89187840.png">

But if I add `inverse = TRUE` to line 30: `Mask <- raster::mask(env.data[[1]], sc, inverse = TRUE)`, this is the result:
<img width="588" alt="Screenshot 2019-11-25 at 15 09 19" src="https://user-images.githubusercontent.com/37101570/69547284-930f0400-0f95-11ea-80a4-69e51fcef1c8.png">

I actually think these pseudo absences still are too close to the observed locations (doesn't seem to be 2 degrees), but at least they're not _at_ the observed locations. But this might be due to the format of input coordinates (in this case lat/long in WGS84).

**Comment by sylvainschmitt** [comment]
@hooge104 , I like your demonstration but you are wrong because you made a quick assumption. 
> I think the issue lies in the selection of PA points (2°far method; Barbet-Massin 2012). 

The method called `disk` in pseudo-absence selection refers to the the ‘1°far’ method of Barbet-Massin 2012 and not the 2°far method. It is precised in our [article](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12841): 
>  the selection strategy: either within the extent of the set of environmental rasters or within a user‐specified distance from each presence

We didn't implement all the strategies described in Barbet-Massin 2012 (only random and 1°far). But you just provided us with the code for the 2°far method, so I invite you to add it to the package with a Pull Request. We made this choice because as you can see on your nice maps, 2°far is very similar to random. The idea behind 1°far is to force the pseudo-absences to be not to environmentally divergent from the observed occurrences.
