### ISSUE TITLE
Maxent projection to different area

### ISSUE THREAD

**Issue by lukasbaumbach** [sylvainschmitt/SSDM#70]
The way the SSDM `project` function works right now, it builds (or - in the case of projecting to a new environment - it re-builds) the original models in their native format with the internal function `get_model` before using `predict`. For MaxEnt this is problematic, if one doesn't want to build a new model with a different environment, but project an existing model (essentially `project` should be a wrapper for `predict`). When I still try to `project` to a new area, if enough training data points fall outside the extent of the new area, the code fails with the error  `Error in .local(x, p, ...) :   more than half of the absence points have NA predictor values`.

As of now, the only workaround I can think of is first "getting" the model with the original set of environmental rasters. Afterwards, one may manually project them using raster's `predict` function.
Of course this is tedious and quite an ugly solution.
 I understand `get_model` is only used as a "hub" to all the algorithms, but in some cases (like this one) it would be good to have the original model available somehow. Then again, re-organising the structure of `.SDM` objects is not really an option. Or can there be an exception for MaxEnt?

@sylvainschmitt Any ideas?

**Comment by sylvainschmitt** [comment]
You don't have to change anything, maybe a quick Skype ? Short explanation in a second post.

**Comment by sylvainschmitt** [comment]
The issue come from the fact that you misused the `Env` argument in the `project` method. The `Env` argument was only included for `Maxent`. Indeed when calling `get_model` all other algorithms only used the `data` slot from the `SDM` object to build the model. But `get_model` for `Maxent` is using the environmental raster stack `Env` passed by `project` to build the model:

https://github.com/sylvainschmitt/SSDM/blob/714b83a0d5bc5bf21ab09445988837aab24b7c8d/R/get_model.R#L114-L124

And I suspect that in your code you used `Env` as the raster stack used to do the projection (which definitely seems logical). But in the case of model forecasting it brings a bug with `Maxent`: the new environment is used both to train the model (`Env` in `get_model`) and project the distribution. In fact this is 2 separate things (training environment = Env0 and projection environment = Env), which are separated for other algorithms (training environment = `SDM@data` and projection environment = `Env` in the  `project` method). **But instead of changing all the code for `Maxent` we can simply change the use of `maxent` function in `get_model` !** Indeed, instead of giving `x` as a raster stack and `p` as spatial points in the `maxent` function, we can directly give `x` as a data frame and `p` as the corresponding occurrences (see [`maxent` documentation](https://www.rdocumentation.org/packages/dismo/versions/1.1-4/topics/maxent)). This should solve your issue without modifying the rest of the code. If you implement that can you further remove the `Env` argument from the `get_model` method for `Maxent` to avoid any future confusion.

**Comment by lukasbaumbach** [comment]
fixed in new version
