### ISSUE TITLE
Stack ensembles with different variables

### ISSUE THREAD

**Issue by asierrl** [sylvainschmitt/SSDM#71]
I've been trying to stack several ESDMs with different environmental variables, but I get this error for each of the ESDMs:

Error in match.names(clabs, names(xi)) : 
  names do not match previous names

I guess that means that ESDMs with different environmental variables cannot be stacked...is it so? I've been looking for information on the issue without success.
And the issue is that the error appears on the variable importance comparison step... The rest of the slots in the SSDM are correctly populated, except for algorithm evaluation (which I assume is calculated after variable importance). Does that mean that those results are valid? 
Best regards,
Asier

**Comment by sylvainschmitt** [comment]
The error is too generic for me to help you directly. I'm guessing you are using the `stacking` function to stack all you ESDMs ? Interestingly, the code is not checking if the environmental variables are the same this is why you can have a half of the results. But at some points it creates a bug.
 
Besides I can totally see the interest, SSDM was not originally designed  to handle ESDMs with different variables. We could think about it in future implementations, but to do it properly we should adapt the code at different stages. 

Anyway and fortunately for you the variable importance comparison is included in a `try` block. So even if the package can't compute variable importance (because it can't compare it between ESDMs if they don't have the same), it throw a message but continue to compute the rest of the step. **So yes the rest of the results are valid.**

So thank you because I didn't know that the package would be able to deal with this specific case.

**Comment by asierrl** [comment]
Thanks to you, Sylvain...this is a pretty piece of code!!
