### ISSUE TITLE
maximum of 30 species?

### ISSUE THREAD

**Issue by xiaofei-liui** [sylvainschmitt/SSDM#73]
Hi, I'm working on a computing task include 99 species data, but the final SSDM can only contain 30 species.
Are there any parameters that need to be set?
By the way, I'm using the GUI.
Thanks a lot!

**Comment by lukasbaumbach** [comment]
Hi!

Did you check the model selection threshold? You can find it in the "intermediate" tab of the "Modelling" page for Stack modelling (first choose an "Ensemble selection metric", below you can set the value with a slider). By default it's only selecting models with an AUC>=0.75, so some of your species models might have fallen below that. Try reducing it to the lowest value (0.5) and see what happens.

In general there should be no upper limit for the number of species you can use (anything your RAM can handle). I can't speak from experience, though, since I never used that many species.

**Comment by sylvainschmitt** [comment]
I couldn't have said better ! Thanks @lukasbaumbach .
