### ISSUE TITLE
Variables normalizatyion and model forecasting

### ISSUE THREAD

**Issue by iuliangherghel** [sylvainschmitt/SSDM#76]
I am trying using SSDM for modeling the species distributions of spadefoot species and I attempted to transfer the models onto mid-Holocene, and Last Glacial Maximum scenarios but I'm getting the following error:

```
Sbombi_midHolocene <- project(Sbombi,midHolocene)
Error in project(Sbombi, midHolocene) : xy not numeric
```
 
The object Sbombi is an Ensemble.SDM (I excluded Maxent)

I also used the following suggestion that I've found on git-hub:
```
project_internal <- function(x, y) project(x, y)
environment(project_internal) <- asNamespace("SSDM")
SDM2 <- project_internal(Sbombi,midHolocene)
plot(SDM2)
```
However, I'm getting identical models (even after I changed in `load_var` function `tmp = FALSE`) with the ones I trained the models.

**Comment by sylvainschmitt** [comment]
> Error in project(Sbombi, midHolocene) : xy not numeric

I think it's explicit. Can you provide a summary of `midHolocene` data ? You don't need anymore the GitHub hack but you can use `project` to do model forecasting in LGM scenarii. I'm not an expert on the new function (maybe @lukasbaumbach  may help), but it seems to me that you are using correctly the function: `project(ESDM, newEnv)` but that there is simply an issue with you descriptors.

**Comment by iuliangherghel** [comment]
Thank you for your quick reply.

`midHolocene`
class      : RasterStack 
dimensions : 1309, 2203, 2883727, 8  (nrow, ncol, ncell, nlayers)
resolution : 0.04166667, 0.04166667  (x, y)
extent     : -139.3381, -47.54642, 5.927126, 60.4688  (xmin, xmax, ymin, ymax)
crs        : NA 
names      :       bio_10,       bio_12,       bio_15,        bio_2,        bio_3,        bio_6,        bio_8,        bio_9 
min values : -0.144846797,  0.005864147,  0.027777778,  0.173708920,  0.183908046, -1.504347826, -0.429429429, -0.806060606 
max values :            1,            1,            1,            1,            1,            1,            1,            1

**Comment by sylvainschmitt** [comment]
Ok it's a bit hard without a reproducible example. Especially the `Error in project(Sbombi, midHolocene) : xy not numeric`  is hard to interpret as we don't have an object named `xy` in our code, so it comes from elsewhere. Could you trace the error ? In addition could you give a summary of the environmental dataset used to train the model to see if they match. And also a summary of the data used to build the ESDM within the object, *i.e.* `summary(Sbombi@data)`.

**Comment by iuliangherghel** [comment]
Thank you for your suggestions, Sylvain. I've tried to trace the problem to raster package; although this was my best guess, I couldn't find the solution there either.

Please find bellow the summary of the data and ESDMs:

Summary of the training layers
`present`
class      : RasterStack 
dimensions : 1309, 2203, 2883727, 8  (nrow, ncol, ncell, nlayers)
resolution : 0.04166667, 0.04166667  (x, y)
extent     : -139.3381, -47.54642, 5.927126, 60.4688  (xmin, xmax, ymin, ymax)
crs        : NA 
names      :      bio_10,      bio_12,      bio_15,       bio_2,       bio_3,       bio_6,       bio_8,       bio_9 
min values : -0.04444444,  0.00600446,  0.03623188,  0.15962441,  0.18604651, -1.48917749, -0.40662651, -0.80547112 
max values :           1,           1,           1,           1,           1,           1,           1,           1 

Summary of the ESDM
`summary(Sbombi@data)`
       X                 Y             Presence          bio_10           bio_12            bio_15       
 Min.   :-137.11   Min.   : 8.574   Min.   :0.0000   Min.   :0.1028   Min.   :0.01064   Min.   :0.04348  
 1st Qu.:-106.19   1st Qu.:34.503   1st Qu.:0.0000   1st Qu.:0.4556   1st Qu.:0.07034   1st Qu.:0.26812  
 Median :-100.81   Median :38.962   Median :0.0000   Median :0.6222   Median :0.09333   Median :0.36957  
 Mean   : -98.80   Mean   :40.517   Mean   :0.4462   Mean   :0.5797   Mean   :0.11317   Mean   :0.35732  
 3rd Qu.: -94.62   3rd Qu.:47.365   3rd Qu.:1.0000   3rd Qu.:0.7028   3rd Qu.:0.14085   3rd Qu.:0.44203  
 Max.   : -53.14   Max.   :60.040   Max.   :1.0000   Max.   :0.9306   Max.   :0.70938   Max.   :0.88406  
     bio_2            bio_3            bio_6             bio_8             bio_9         
 Min.   :0.1878   Min.   :0.1977   Min.   :-1.4719   Min.   :-0.3072   Min.   :-0.79027  
 1st Qu.:0.5493   1st Qu.:0.3372   1st Qu.:-0.6970   1st Qu.: 0.4157   1st Qu.:-0.17325  
 Median :0.6479   Median :0.4186   Median :-0.3896   Median : 0.5904   Median : 0.01216  
 Mean   :0.6441   Mean   :0.4154   Mean   :-0.4374   Mean   : 0.5276   Mean   : 0.05236  
 3rd Qu.:0.7465   3rd Qu.:0.4767   3rd Qu.:-0.1645   3rd Qu.: 0.6928   3rd Qu.: 0.31003  
 Max.   :0.9437   Max.   :0.9302   Max.   : 0.9740   Max.   : 0.9940   Max.   : 0.89058  

Thank you

**Comment by sylvainschmitt** [comment]
Wow it took me times but everything is here ! Please try to inspect on your side every element before asking help from the developers. I was focus on the R error, but everything is said here :

> However, I'm getting identical models

Indeed if you look at the variation of variable bio10 on current and past climate you will see it always vary between -0.something to 1. So you make slightly the same prediction in both cases (they are not identical as you quickly said because they do not vary exactly in the same way). And this is due to the fact that you are using `load_var` function with the option `Norm = TRUE` (default). So each time your variable is transformed and the model can't predict in the past. Run model building and projection with environmental data loaded with `Norm = FALSE`  and everything should be fine.

**Comment by sylvainschmitt** [comment]
@lukasbaumbach maybe we should add something in the function description or put `Norm = FALSE` as default in `load_var` because the error seems easy to make

**Comment by iuliangherghel** [comment]
Thank you for your feedback. Now it makes more sense and works with  `project_internal` function. Cheers!

**Comment by sylvainschmitt** [comment]
Ok, let's hope it will help other useR and that your experience may improve package default value to avoid recurrent useR errors.

**Comment by sylvainschmitt** [comment]
> Thank you for your feedback. Now it makes more sense and works with `project_internal` function. Cheers!

You mean it didn't work with the `project` function alone and that you had to use the `project_internal` trick ?

**Comment by iuliangherghel** [comment]
Yes, the `project `function keeps giving me the same error (xy not numeric) despite loading the variables as suggested, and I'm using the `project_internal` trick and it works.

Also, I also checked the first two models I initially claimed were identical by applying a correlation between the output ensembles of mid Holocene and present and were indeed identical (r=1). The workaround was to clear the R console and load the variables and run the models again. After I've done that (clearing the R console and starting clean), I got the actual model transfer. I hope this helps other useR. 

Also, any suggestions (workarounds) in how to project Maxent models in SSDM?

**Comment by lukasbaumbach** [comment]
> @lukasbaumbach maybe we should add something in the function description or put `Norm = FALSE` as default in `load_var` because the error seems easy to make

Sorry for joining the party late, I was at a conference last week. So... yes, one has to be careful with normalizing the environmental predictors for model training and projection, because the normalization is always relative to the input value range. So if you want to project beyond the training area or over time, you would need to normalize considering the min-max value range of the new environment as well (this method may have its own limitations though). 
In this regard, yes, we might want to set the default `norm` argument to `FALSE`.

The `Error in project(Sbombi, midHolocene) : xy not numeric` doesn't sound familiar to me, but I would agree with Sylvain, that you should go looking for a layer or object called `xy`.

> Also, any suggestions (workarounds) in how to project Maxent models in SSDM?

We're currently developing the next version of SSDM, which will bring a whole lot of improvements and added functionality (including a fix for Maxent). To be released soon (will be worth the wait!).
In the meantime you could try the following: since `project` is basicly a wrapper for the `predict` function, you may manually use `SSDM:::get_model(model, Env)` to retrieve the original model and then project it to a new environment using the `predict` function.

**Comment by sylvainschmitt** [comment]
> Sorry for joining the party late, I was at a conference last week. 

Don't apologize we are developing SSDM for free, it's not your primary job !

> In this regard, yes, we might want to set the default norm argument to FALSE.

To do for next version.

> The Error in project(Sbombi, midHolocene) : xy not numeric

Yes I hope it came from the user side and that there aren't an hidden bug in the new `project` method for `ESDM`|.

**Comment by marshHawk4** [comment]
I had this error for a different situation and solved it by specifying the library before calling project. So in my case the project function I wanted to use was from a library called rmaxent::project().  I am under the impression there is another library that has a project() function that is overwritting the function and giving back the `xy not numeric` error.
